"""empty message

Revision ID: 541c5eb42f34
Revises: 
Create Date: 2024-05-08 10:33:22.297495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541c5eb42f34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_number', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('img_creation_time', sa.String(length=64), nullable=True),
    sa.Column('img_creation_date', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('cut_file', sa.Boolean(), nullable=False),
    sa.Column('format', sa.String(length=64), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_file_path'), ['file_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_img_creation_date'), ['img_creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_img_creation_time'), ['img_creation_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_timestamp'), ['timestamp'], unique=False)

    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('url_test', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model'))
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status'))
    )
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_timestamp'), ['timestamp'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_notification_image_id_images')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_timestamp'), ['timestamp'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('cutting_images_size', sa.Text(), nullable=True),
    sa.Column('percentage_white', sa.Integer(), nullable=True),
    sa.Column('percentage_black', sa.Integer(), nullable=True),
    sa.Column('color_for_draw_rectangle', sa.Text(), nullable=True),
    sa.Column('color_for_draw_text', sa.Text(), nullable=True),
    sa.Column('user_reloading_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_settings_model_id_model')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('settings_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['settings_id'], ['settings.id'], name=op.f('fk_user_settings_id_settings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('predict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('result_all_mitoz', sa.Integer(), nullable=True),
    sa.Column('result_max_mitoz_in_one_img', sa.String(length=128), nullable=True),
    sa.Column('count_img', sa.Integer(), nullable=True),
    sa.Column('name_img_have_max_mitoz', sa.String(length=512), nullable=True),
    sa.Column('path_to_save', sa.String(length=512), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_predict_image_id_images')),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_predict_model_id_model')),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], name=op.f('fk_predict_status_id_status')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_predict_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predict'))
    )
    with op.batch_alter_table('predict', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predict_timestamp'), ['timestamp'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('predict_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_task_image_id_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['predict_id'], ['predict.id'], name=op.f('fk_task_predict_id_predict'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_task_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_timestamp'))
        batch_op.drop_index(batch_op.f('ix_task_name'))

    op.drop_table('task')
    with op.batch_alter_table('predict', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predict_timestamp'))

    op.drop_table('predict')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('settings')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_timestamp'))
        batch_op.drop_index(batch_op.f('ix_notification_name'))

    op.drop_table('notification')
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_timestamp'))
        batch_op.drop_index(batch_op.f('ix_status_name'))

    op.drop_table('status')
    op.drop_table('model')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_timestamp'))
        batch_op.drop_index(batch_op.f('ix_images_name'))
        batch_op.drop_index(batch_op.f('ix_images_img_creation_time'))
        batch_op.drop_index(batch_op.f('ix_images_img_creation_date'))
        batch_op.drop_index(batch_op.f('ix_images_file_path'))

    op.drop_table('images')
    # ### end Alembic commands ###
